version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ncadmin
      - MYSQL_PASSWORD=ncadmin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: .
    restart: always
    ports:
      - 8443:443
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./scripts/pre-installation:/docker-entrypoint-hooks.d/pre-installation
      - ./scripts/post-installation:/docker-entrypoint-hooks.d/post-installation
      - ./nextcloud_apps/twofactor_webeid:/var/www/html/custom_apps/twofactor_webeid
    environment:
      - MYSQL_PASSWORD=ncadmin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=ncadmin
      - NEXTCLOUD_ADMIN_PASSWORD=ncadmin
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
